import styles from "./page.module.scss";
import Work from "./components/work/Work";
import ResponsiveBio from "./components/responsive home/ResponsiveBio";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div className={styles.home}>
      <div className={styles.work}>
        <Work />
      </div>
      <div className={styles.responsiveBio}>
        <ResponsiveBio />
      </div>
    </div>
  );
}
